{- git-annex build info
 -
 - Copyright 2013-2017 Joey Hess <id@joeyh.name>
 -
 - Licensed under the GNU GPL version 3 or higher.
 -}

{-# LANGUAGE CPP #-}

module BuildInfo where

-- This file is generated by the configure program with the results of its
-- probing.
#include "Build/SysConfig"
-- This file is automatically generated from the CHANGELOG version
#include "Build/Version"
