flags:
  git-annex:
    production: true
    parallelbuild: true
    assistant: true
    pairing: true
    torrentparser: true
    magicmime: false
    dbus: false
    debuglocks: false
    benchmark: true
    crypton: true
packages:
- '.'
resolver: lts-22.9
extra-deps:
allow-newer: true
