flags:
  git-annex:
    production: true
    parallelbuild: true
    assistant: true
    pairing: true
    torrentparser: true
    magicmime: false
    dbus: false
    debuglocks: false
    benchmark: true
    crypton: false
packages:
- '.'
resolver: nightly-2023-08-01
extra-deps:
- git-lfs-1.2.1
- http-client-restricted-0.1.0
- torrent-10000.1.1
- bencode-0.6.1.1
- feed-1.3.2.1
- bloomfilter-2.0.1.2
allow-newer: true
