flags:
  git-annex:
    production: true
    parallelbuild: true
    assistant: true
    pairing: true
    torrentparser: true
    magicmime: false
    dbus: false
    debuglocks: false
    benchmark: true
    crypton: true
    servant: true
    ospath: true
packages:
- '.'
resolver: nightly-2025-04-04
extra-deps:
- feed-1.3.2.1
allow-newer: true
allow-newer-deps:
- feed
