flags:
  git-annex:
    production: true
    assistant: true
    pairing: true
    torrentparser: true
    magicmime: false
    dbus: false
    debuglocks: false
    benchmark: true
    gitlfs: true
packages:
- '.'
resolver: lts-19.33
extra-deps:
- IfElse-0.85
- aws-0.24
- bloomfilter-2.0.1.0
- git-lfs-1.2.0
- http-client-restricted-0.0.5
- network-multicast-0.3.2
- sandi-0.5
- torrent-10000.1.1
- Win32-2.11.1.0
