flags:
  git-annex:
    production: true
    parallelbuild: true
    assistant: true
    pairing: true
    torrentparser: true
    magicmime: false
    dbus: false
    debuglocks: false
    benchmark: true
    ospath: true
packages:
- '.'
resolver: lts-24.2
extra-deps:
- aws-0.25
