flags:
  git-annex:
    production: true
    parallelbuild: true
    assistant: true
    pairing: true
    torrentparser: true
    magicmime: false
    dbus: false
    debuglocks: false
    benchmark: true
    crypton: true
    servant: true
    osstring: true
packages:
- '.'
resolver: nightly-2025-01-20
extra-deps:
- filepath-bytestring-1.5.2.0.2
- aws-0.24.4
- git-lfs-1.2.3
- feed-1.3.2.1
allow-newer: true
allow-newer-deps:
- feed
