#!/usr/bin/env bash
set -eux -o pipefail

function api_call {
    curl -fsSL \
        -H "Authorization: bearer $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        "$@"
}

INPUT_PR="$1"
OSNAME="$2"
JOBNAME="$3"
STATE="$4"

if [ "$STATE" = cancelled ]
then STATE=error
fi

JOBS="$(api_call "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs")"

JOB_URL="$(jq -r --arg job "$JOBNAME" '.jobs[] | select(.name == $job) | .html_url' <<<"$JOBS")"

if [ -z "$JOB_URL" ]
then echo "[WARNING] Could not determine job URL"
     echo "[INFO] Expected job with name: '$JOBNAME'"
     echo "[INFO] Found jobs with names:"
     jq '.jobs | [.[].name]' <<<"$JOBS"
fi

STATUSES_URL="$(api_call "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/pulls/$INPUT_PR" | jq -r .statuses_url)"

jq -n \
    --arg context "Build git-annex on $OSNAME / $JOBNAME" \
    --arg state "$STATE" \
    --arg target_url "$JOB_URL" \
    '{
        "state": $state,
        "context": $context,
        "target_url": $target_url
    }' \
| api_call -X POST -H "Content-Type: application/json" -d @- "$STATUSES_URL"
