#!/usr/bin/env bash
set -eux -o pipefail
export GH_PAGER=cat

INPUT_PR="$1"
OSNAME="$2"
JOBNAME="$3"
STATE="$4"

if [ "$STATE" = cancelled ]
then STATE=error
fi

JOBS="$(gh api "repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs")"

JOB_URL="$(jq -r --arg job "$JOBNAME" '.jobs[] | select(.name == $job) | .html_url' <<<"$JOBS")"

if [ -z "$JOB_URL" ]
then echo "[WARNING] Could not determine job URL"
     echo "[INFO] Expected job with name: '$JOBNAME'"
     echo "[INFO] Found jobs with names:"
     jq '.jobs | [.[].name]' <<<"$JOBS"
fi

STATUSES_URL="$(gh api --jq .statuses_url "repos/$GITHUB_REPOSITORY/pulls/$INPUT_PR")"

jq -n \
    --arg context "Build git-annex on $OSNAME / $JOBNAME" \
    --arg state "$STATE" \
    --arg target_url "$JOB_URL" \
    '{
        "state": $state,
        "context": $context,
        "target_url": $target_url
    }' \
| gh api -X POST --input - "$STATUSES_URL"
