#!/bin/bash
#
set -eu

name="$1"
size="$2"

case `uname` in
    Linux)
        sudo apt-get update -qq
        sudo apt-get install dosfstools

        image="/tmp/$name.img"

        # VFAT FS in a box
        sudo dd if=/dev/zero "of=$image" "count=$size" bs=1M
        sudo mkfs.vfat "$image"

        # mount
        CRIPPLEDFS_PATH="/$name"
        sudo mkdir "$CRIPPLEDFS_PATH"
        sudo mount -o "uid=$(id -u),gid=$(id -g)" "$image" "$CRIPPLEDFS_PATH"
        ;;
    Darwin)
        image="/tmp/$name.dmg"
        hdiutil create -megabytes "$size" -fs FAT32 -volname "$name" "$image"
        hdiutil attach "$image"
        CRIPPLEDFS_PATH="/Volumes/$name"
        ;;
    *)
        echo "Unknown OS $(uname)"
        exit 1
esac

unset name
unset size
unset image
