#!/bin/sh
link="$(readlink -f "$0" 2>/dev/null || readlink "$0")" || true
if [ -n "$link" ]; then
	base="$(dirname "$link")"
else
	base="$(dirname "$0")"
fi

if [ ! -d "$base" ]; then
	echo "** cannot find base directory (I seem to be $0)" >&2
	exit 1
fi
if [ ! -e "$base/runshell" ]; then
	echo "** cannot find $base/runshell" >&2
	exit 1
fi

# Get absolute path to base, to avoid breakage when things change directories.
orig="$(pwd)"
cd "$base"
base="$(pwd)"
cd "$orig"

exec "$base/runshell" git-shell "$@"
