#!/bin/bash
#
# A little helper script to build a package with standalone git-annex
# It relies on being run within git-annex's git repository
#
set -eu

umask 022

# For NeuroDebian we rely on `git describe` output to get a
# sortable version which should work for any stage of a snapshot between
# releases and would remain sortable
ANNEX_VERSION=$(git describe HEAD)
ANNEX_NDVERSION=$( echo ${ANNEX_VERSION} | sed -e 's,-,+git,' -e 's,$,-1~ndall+1,')

dch --noconf -v ${ANNEX_NDVERSION} \
    --force-bad-version --force-distribution -D neurodebian "Backported fresh snapshot"
