#!/bin/sh
# Runs inside the chroot set up by buildchroot, as the user it creates
set -e
set -x

# Put in /tmp by buildchroot, but when bootstrapping with propellor,
# this is run inside a checked out git-annex tree.
if [ -e /tmp/abiversion ]; then
	ABIVERSION=$(cat /tmp/abiversion)
else
	ABIVERSION=$(cat standalone/android/abiversion)
fi

cd
rm -rf .ghc .cabal .android
cabal update
cabal install happy alex --bindir=$HOME/bin
PATH=$HOME/bin:$PATH
export PATH
mkdir -p .android
cd .android
git clone https://github.com/joeyh/ghc-android
cd ghc-android
git checkout stable-ghc-snapshot
./build

# This saves 2 gb, and the same sources are in build-*/ghc
rm -rf stage0

# Set up android SDK where the git-annex android Makefile
# expects to find it.
cd ..
ln -s ghc-android/android-ndk-* android-ndk
wget http://dl.google.com/android/adt/adt-bundle-linux-x86-20130917.zip
unzip adt*.zip
rm adt*.zip
mv adt-bundle-linux-x86-* adt-bundle-linux-x86
rm -rf adt-bundle-linux-x86/eclipse

# The git-annex android Makefile needs this cc symlink.
ln -s arm-linux-androideabi-gcc $HOME/.ghc/$ABIVERSION/bin/cc

git config --global user.email androidbuilder@example.com
git config --global user.name androidbuilder
