#!/bin/sh
base="$(dirname $0)"
if [ ! -d "$base" ]; then
	echo "** cannot find base directory (I seem to be $0)" >&2
	exit 1
fi
if [ ! -e "$base/runshell" ]; then
	echo "** cannot find $base/runshell" >&2
	exit 1
fi
"$base/runshell" git-annex webapp "$@"
