#!/bin/sh
base="$(dirname $0)"
if [ ! -d "$base" ]; then
	echo "** cannot find base directory (I seem to be $0)" >&2
	exit 1
fi
if [ ! -e "$base/runshell" ]; then
	echo "** cannot find $base/runshell" >&2
	exit 1
fi

# If this is a standalone app, set a variable that git-annex can use to
# install itself.
if [ -e "$base/bin/git-annex" ]; then
	GIT_ANNEX_OSX_APP_BASE="$base"
	export GIT_ANNEX_OSX_APP_BASE
fi

"$base/runshell" git-annex webapp "$@"
