#!/bin/sh
set -e

base="$(dirname $0)"

if [ ! -d "$base" ]; then
	echo "** cannot find base directory (I seem to be $0)" >&2
	exit 1
fi

if [ ! -e "$base/bin/git-annex" ]; then
	echo "** base directory $base does not contain bin/git-annex" >&2
	exit 1
fi
if [ ! -e "$base/bin/git" ]; then
	echo "** base directory $base does not contain bin/git" >&2
	exit 1
fi

# Get absolute path to base, to avoid breakage when things change directories.
orig="$(pwd)"
cd "$base"
base="$(pwd)"
cd "$orig"

# Put our binaries first, so our overloaded libs don't get used with
# system binaries.
# Also avoids issues with out of date system binaries.
PATH=$base/bin:$PATH
export PATH

for lib in "$(cat libdirs)"; do
	DYLD_LIBRARY_PATH="$base/$lib:$DYLD_LIBRARY_PATH"
done
export DYLD_LIBRARY_PATH

GIT_EXEC_PATH=$base/git-core
export GIT_EXEC_PATH

if [ "$1" ]; then
	cmd="$1"
	shift 1
	"$cmd" "$@"
else
	$SHELL
fi
