name: Trigger build workflows for active pull requests

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Use Python 3.8+
        uses: actions/setup-python@v2
        with:
          python-version: '^3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pip-run wheel
          # No quotes around substitution:
          python -m pip install $(python -m pip_run.read-deps .github/workflows/tools/prdispatch.py)
          # Install the script's dependencies beforehand in order to reduce
          # time between the start of the "Run PR workflow dispatch script"
          # step and the script actually executing, lest any PR events
          # occurring in that window be counted twice by two separate runs.

      # IMPORTANT: Any change to the name of this step MUST be reflected in the
      # `THIS_STEP` variable in `prdispatch.py`!
      - name: Run PR workflow dispatch script
        run: python .github/workflows/tools/prdispatch.py
        env:
          GITHUB_TOKEN: ${{ secrets.DATALAD_GITHUB_TOKEN }}

# vim:set sts=2:
